[package]
name = "compact_str-fuzz"
version = "0.0.0"
authors = ["Parker Timmerman <parker@parkertimmerman.com>"]
publish = false
edition = "2018"

[package.metadata]
cargo-fuzz = true

[dependencies]
arbitrary = { version = "1", features = ["derive"] }
bytes = "1"
compact_str = { path = "../compact_str", features = ["bytes"] }
libfuzzer-sys = "0.4"

[[bin]]
name = "compact_str"
path = "fuzz_targets/compact_str.rs"
test = false
doc = false
