on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:

name: CI

env:
  RUSTFLAGS: "-D warnings"

jobs:
  check:
    name: cargo check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true
      - uses: actions-rs/cargo@v1
        with:
          command: check
          args: --all-features

  test:
    name: cargo test
    runs-on: ubuntu-latest
    env:
      PROPTEST_CASES: 500
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true
      - uses: actions-rs/cargo@v1
        with:
          command: test
          args: --all-features

  test-nightly:
    name: cargo test nightly
    runs-on: ubuntu-latest
    env:
      PROPTEST_CASES: 500
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: nightly
          override: true
      - uses: actions-rs/cargo@v1
        with:
          command: test
          args: --all-features

  miri:
    name: cargo miri test
    runs-on: ubuntu-latest
    env:
      # We reduce the number of "randomized runs" because Miri is quite slow
      RANDOMIZED_RUNS: 1000
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: nightly
          override: true
          components: miri
      - name: Run Miri
        run: |
          cargo miri test

  example-bytes:
    name: example - bytes
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: nightly
          override: true
      - uses: actions-rs/cargo@v1
        with:
          command: run
          args: --manifest-path examples/bytes/Cargo.toml

  example-serde:
    name: example - serde
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: nightly
          override: true
      - uses: actions-rs/cargo@v1
        with:
          command: run
          args: --manifest-path examples/serde/Cargo.toml
