on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:

name: CI

env:
  CARGO_TERM_COLOR: "always"
  RUSTFLAGS: "-D warnings"
  PROPTEST_CASES: 10000
  MIRIFLAGS: "-Zmiri-strict-provenance -Zmiri-check-number-validity"

jobs:
  check:
    name: cargo check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true
      - uses: actions/cache@v3
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            target/
          key: ${{ runner.os }}-${{ hashFiles('**/Cargo.toml') }}-stable-check
          restore-keys: |
            ${{ runner.os }}-${{ hashFiles('**/Cargo.toml') }}-stable
      - uses: actions-rs/cargo@v1
        with:
          command: check
          args: --tests --all-features

  test:
    name: cargo test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true
      - uses: actions/cache@v3
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            target/
          key: ${{ runner.os }}-${{ hashFiles('**/Cargo.toml') }}-stable-test
          restore-keys: |
            ${{ runner.os }}-${{ hashFiles('**/Cargo.toml') }}-stable
      - name: Install cargo-nextest
        uses: taiki-e/install-action@nextest
      - name: cargo test
        run: |
          cargo nextest run --release --all-features --manifest-path=compact_str/Cargo.toml --run-ignored=all

  test-nightly:
    name: cargo test nightly
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/cache@v3
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            target/
          key: ${{ runner.os }}-${{ hashFiles('**/Cargo.toml') }}-nightly-test
          restore-keys: |
            ${{ runner.os }}-${{ hashFiles('**/Cargo.toml') }}-nightly
      - name: Install cargo-nextest
        uses: taiki-e/install-action@nextest
      # Install nightly after cargo-nextest is installed, as cargo-nextest failed to compile on nightly
      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: nightly
          override: true
      - name: cargo test
        run: |
          cargo nextest run --release --all-features --manifest-path=compact_str/Cargo.toml --run-ignored=all

  miri:
    name: cargo miri test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: nightly
          override: true
          components: miri
      - uses: actions/cache@v3
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            target/
          key: ${{ runner.os }}-${{ hashFiles('**/Cargo.toml') }}-nightly-test-miri
          restore-keys: |
            ${{ runner.os }}-${{ hashFiles('**/Cargo.toml') }}-nightly-test
            ${{ runner.os }}-${{ hashFiles('**/Cargo.toml') }}-nightly
      - name: Run Miri
        run: |
          cargo miri test --all-features --manifest-path=compact_str/Cargo.toml

  randomize-layout:
    name: cargo test -Zrandomize-layout
    runs-on: ubuntu-latest
    env:
      RUSTFLAGS: -Zrandomize-layout
    steps:
      - uses: actions/checkout@v3
      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: nightly
          override: true
      - uses: actions/cache@v3
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            target/
          key: ${{ runner.os }}-${{ hashFiles('**/Cargo.toml') }}-nightly-test-randomize-layout
          restore-keys: |
            ${{ runner.os }}-${{ hashFiles('**/Cargo.toml') }}-nightly-test
            ${{ runner.os }}-${{ hashFiles('**/Cargo.toml') }}-nightly
      - name: Run Tests with Randomized Layout
        run: |
          cargo test --all-features --manifest-path=compact_str/Cargo.toml

  examples:
    name: example
    runs-on: ubuntu-latest
    strategy:
      matrix:
        ex: ["bytes", "macros", "serde", "traits"] 
    steps:
      - uses: actions/checkout@v3
      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: nightly
          override: true
      - uses: actions/cache@v3
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            target/
          key: ${{ runner.os }}-${{ hashFiles('**/Cargo.toml') }}-nightly-example-${{ matrix.ex }}
          restore-keys: |
            ${{ runner.os }}-${{ hashFiles('**/Cargo.toml') }}-nightly-example
            ${{ runner.os }}-${{ hashFiles('**/Cargo.toml') }}-nightly
      - uses: actions-rs/cargo@v1
        with:
          command: run
          args: --manifest-path examples/${{ matrix.ex }}/Cargo.toml
