on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:

name: X-Plat

env:
  # local default for proptest is 100
  PROPTEST_CASES: 1000
  RUSTFLAGS: "-D warnings"

jobs:
  windows:
    name: Windows
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
        name: Checkout Repo
      - uses: actions-rs/toolchain@v1
        name: Install Rust
        with:
          profile: minimal
          toolchain: stable
          override: true
          components: miri
      - uses: actions-rs/cargo@v1
        name: cargo test
        with:
          command: test
          args: --release --all-features --manifest-path=compact_str/Cargo.toml -- --include-ignored
      - uses: actions-rs/cargo@v1
        name: cargo test miri
        with:
          command: test
          args: --all-features --manifest-path=compact_str/Cargo.toml

  macos:
    name: macOS
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
        name: Checkout Repo
      - uses: actions-rs/toolchain@v1
        name: Install Rust
        with:
          profile: minimal
          toolchain: stable
          override: true
          components: miri
      - uses: actions-rs/cargo@v1
        name: cargo test
        with:
          command: test
          args: --release --all-features --manifest-path=compact_str/Cargo.toml -- --include-ignored
      - uses: actions-rs/cargo@v1
        name: cargo test miri
        with:
          command: test
          args: --all-features --manifest-path=compact_str/Cargo.toml

  linux_arm7:
    name: Linux ARMv7
    runs-on: [self-hosted, linux, ARM]
    steps:
      - uses: actions/checkout@v2
        name: Checkout Repo
      - uses: actions-rs/toolchain@v1
        name: Install Rust
        with:
          profile: minimal
          toolchain: stable
          override: true
          components: miri
      - uses: actions-rs/cargo@v1
        name: cargo test
        with:
          command: test
          args: --release --all-features --manifest-path=compact_str/Cargo.toml
      - uses: actions-rs/cargo@v1
        name: cargo test miri
        with:
          command: test
          args: --all-features --manifest-path=compact_str/Cargo.toml

  linux_32bit:
    name: Linux 32-bit
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        name: Checkout Repo
      - uses: actions-rs/toolchain@v1
        name: Install Rust
        with:
          toolchain: stable
          target: i686-unknown-linux-gnu
          override: true
          components: miri
      - uses: actions-rs/cargo@v1
        name: cargo test
        with:
          use-cross: true
          command: test
          args: --release --all-features --manifest-path=compact_str/Cargo.toml --target i686-unknown-linux-gnu
      - uses: actions-rs/cargo@v1
        name: cargo test miri
        with:
          command: test
          args: --all-features --manifest-path=compact_str/Cargo.toml -- target i686-unknown-linux-gnu

  linux_mips_32bit:
    name: Linux MIPS Big Endian 32-bit
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        name: Checkout Repo
      - uses: actions-rs/toolchain@v1
        name: Install Rust
        with:
          toolchain: stable
          target: mips-unknown-linux-gnu
          override: true
          components: miri
      - uses: actions-rs/cargo@v1
        name: cargo test
        with:
          use-cross: true
          command: test
          args: --release --all-features --manifest-path=compact_str/Cargo.toml --target mips-unknown-linux-gnu
      - uses: actions-rs/cargo@v1
        name: cargo test miri
        with:
          command: test
          args: --all-features --manifest-path=compact_str/Cargo.toml -- target mips-unknown-linux-gnu

  linux_mips_le_32bit:
    name: Linux MIPS Little Endian 32-bit
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          target: mipsel-unknown-linux-gnu
          override: true
      - uses: actions-rs/cargo@v1
        with:
          use-cross: true
          command: test
          args: --release --all-features --manifest-path=compact_str/Cargo.toml --target mipsel-unknown-linux-gnu

  linux_powerpc_bit:
    name: Linux PowerPC Big Endian 32-bit
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          target: powerpc-unknown-linux-gnu
          override: true
      - uses: actions-rs/cargo@v1
        with:
          use-cross: true
          command: test
          args: --release --all-features --manifest-path=compact_str/Cargo.toml --target powerpc-unknown-linux-gnu

  linux_powerpc_le_64bit:
    name: Linux PowerPC Little Endian 64-bit
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          target: powerpc64le-unknown-linux-gnu
          override: true
      - uses: actions-rs/cargo@v1
        with:
          use-cross: true
          command: test
          args: --release --all-features --manifest-path=compact_str/Cargo.toml --target powerpc64le-unknown-linux-gnu -- --include-ignored

  linux_powerpc_bit_miri:
    name: Linux PowerPC Big Endian 32-bit [Miri]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          target: powerpc-unknown-linux-gnu
          override: true
          components: miri
      - uses: actions-rs/cargo@v1
        with:
          command: miri
          args: test --release --all-features --manifest-path=compact_str/Cargo.toml --target powerpc-unknown-linux-gnu
