on:
  workflow_dispatch:
  schedule:
    - cron: '0 01,13 * * *'

name: Fuzz

jobs:
  fuzz_x86_64:
    name: fuzz [x86_64]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        name: Checkout compact_str
      - uses: actions-rs/toolchain@v1
        name: Install Rust
        with:
          profile: minimal
          toolchain: nightly
          override: true
      - uses: actions-rs/install@v0.1
        name: Install cargo-fuzz
        with:
          crate: cargo-fuzz
          version: latest
      - uses: actions-rs/cargo@v1
        name: Fuzz
        with:
          command: fuzz
          args: run --debug-assertions compact_str -- -max_total_time=1200

  # creation_aarch64:
  #   name: creation [aarch64]
  #   runs-on: ubuntu-latest
  #   steps:
  #     - uses: actions/checkout@v2
  #       name: Checkout compact_str
  #     - uses: actions-rs/toolchain@v1
  #       name: Install Rust
  #       with:
  #         toolchain: nightly
  #         target: aarch64-unknown-linux-gnu
  #         override: true
  #     - uses: actions-rs/install@v0.1
  #       name: Install cargo-fuzz
  #       with:
  #         crate: cargo-fuzz
  #         version: latest
  #     - uses: actions-rs/cargo@v1
  #       name: Fuzz
  #       with:
  #         use-cross: true
  #         command: fuzz
  #         args: run --debug-assertions --fuzz-dir compact_str/fuzz --target aarch64-unknown-linux-gnu creation -- -max_total_time=900
