on:
  workflow_dispatch:
  schedule:
    - cron: '0 01,13 * * *'

name: Fuzz

jobs:
  fuzz_64bit:
    name: cargo fuzz 64bit
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: nightly
          override: true
      - uses: actions-rs/install@v0.1
        name: Install cargo-fuzz
        with:
          crate: cargo-fuzz
          version: latest
      - name: Fuzz 64-bit
        run: |
          cd compact_str
          cargo fuzz run creation -- -max_total_time=900

  fuzz_32bit:
    name: cargo fuzz 32bit
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: nightly
          target: i686-unknown-linux-gnu
          override: true
      - uses: actions-rs/install@v0.1
        name: Install cargo-fuzz
        with:
          crate: cargo-fuzz
          version: latest
      - name: Fuzz 32-bit
        run: |
          cd compact_str
          cargo fuzz run creation -- -max_total_time=900
