on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:

name: MSRV

env:
  RUSTFLAGS: "-D warnings"

jobs:
  test:
    name: cargo test msrv..
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          default: true
          toolchain: 1.49
      - name: cargo test msrv..
        run: |
          cd compact_str
          cargo test --all-features
