on:
  workflow_dispatch:
  schedule:
    - cron: '0 01,13 * * *'

name: Randomized

env:
  # local default is 50,000
  # we run 2,000,000,000 in CI because this is a scheduled job and doesn't impact time to merge
  RANDOMIZED_RUNS: 2000000000

jobs:
  linux_64bit:
    name: Linux 64-bit
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true
      - uses: actions-rs/cargo@v1
        with:
          command: test
          args: --release randomized -- --nocapture

  linux_32bit:
    name: Linux 32-bit
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          target: i686-unknown-linux-gnu
          override: true
      - uses: actions-rs/cargo@v1
        with:
          use-cross: true
          command: test
          args: --release randomized --target i686-unknown-linux-gnu -- --nocapture
